### ISSUE TITLE
RSS Feed Displays over time

### ISSUE THREAD

**Issue by angry-bender** [AnotherShen/FORS#1]
![image](https://user-images.githubusercontent.com/18164137/116417343-50ccaf00-a87a-11eb-8ac0-477c3a91d448.png)

**Comment by angry-bender** [comment]
See Pull #2 
![image](https://user-images.githubusercontent.com/18164137/116420894-8aeb8000-a87d-11eb-9ed0-74a1ddd50340.png)

**Comment by AnotherShen** [comment]
Fixed by constraining the RSS feed to a 50% view width.
